---
# Add epel-release repo
- name: Add epel-release repo
  yum:
    name: epel-release
    state: present
# Add zip/unzip
- name: Add zip/unzip
  yum:
    name: "{{ zip_packages }}"
    state: present
# Add Software Collections
- name: Add Software Collections
  yum:
    name: centos-release-scl.noarch
    state: present
# Install PHP 7.3
- name: Install PHP 7.3
  yum:
    name: "{{ php_packages }}"
    state: present
# Set Memory limit
- name: Set Memory limit
  ini_file:
    path: /etc/opt/rh/rh-php73/php.ini
    section: PHP
    option: memory_limit
    value: 1024M
# Enable PHP CLI with link
- name: Enable PHP CLI with link
  file:
    src: /opt/rh/rh-php73/root/usr/bin/php
    dest: /usr/bin/php
    state: link
# Start Php-FPM
- name: Start
  systemd:
    name: rh-php73-php-fpm
    state: started
    enabled: yes
# Copie php-fpm.conf template     
- name: Copie php-fpm.conf template
  template:
    src: php-fpm.conf.j2
    dest: /etc/httpd/conf.d/php-fpm.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart httpd
# Install Composer
- name: Install Composer
  copy:
    src: composer.phar
    dest: /usr/bin/composer
    owner: root
    group: root
    mode: '0755'
