---
# Add epel-release repo
- name: Add epel-release repo
  yum:
    name: epel-release
    state: present
# Add zip/unzip
- name: Add zip/unzip
  yum:
    name: "{{ zip_packages }}"
    state: present

# Install PHP Rpm
- name: Create temporary directory
  file:
    path: /tmp/rpm
    state: directory

- name: copy Rpm to temporary
  copy:
    src: "{{ item }}"
    dest: /tmp/rpm
  with_fileglob:
    - "../files/rpm/*.rpm"
  register: rpms_copied

- set_fact:
    rpm_list: "{{ rpms_copied.results | map(attribute='dest') | list }}"

- name: install RPMs
  yum:
    name: "{{ rpm_list }}"

# Install Composer
- name: Install Composer
  copy:
    src: composer.phar
    dest: /usr/bin/composer
    owner: root
    group: root
    mode: '0755'
