---
# Add epel-release repo
- name: Add epel-release repo
  yum:
    name: epel-release
    state: present
# Add zip/unzip
- name: Add zip/unzip
  yum:
    name: "{{ zip_packages }}"
    state: present
# Add Software Collections
- name: Add Software Collections
  yum:
    name: centos-release-scl.noarch
    state: present
# Install PHP 7.3
- name: Install PHP 7.3
  yum:
    name: rh-php73
    state: present
# Enable PHP with link
- name: Enable PHP with link
  file:
    src: /opt/rh/rh-php73/root/usr/bin/php
    dest: /usr/bin/php
    state: link
# Install Composer
- name: Install Composer
  copy:
    src: composer.phar
    dest: /usr/bin/composer
    owner: root
    group: root
    mode: '0755'
